language: rust
before_install:
  - sudo apt update
  - sudo apt install -y libasound2-dev
  - sudo apt-get install -y libudev-dev
  - sudo apt install -y pkg-config
script:
  - cargo fmt -- --check
  - cargo build --verbose --workspace
  - cargo test --verbose
